### PR TITLE
Add custom attributes to mediafile

### PR DESCRIPTION
**Pull request by davidbonting**
First of all great work Sokil!

The only problem I have that this package isn't that flexible. For example: every attribute for a MediaFile has it's own function. I could have written more functions, but I wanted something more flexible.

So I created a "custom" attribute function where you could pass in everything you want. Of course this means you could break the VAST tag spec, but that's a users own choice.

### CODE REVIEW

**Review by sokil — CHANGES_REQUESTED** [review]
Thank you for contribution and sorry for late response. Idea of this library to make a tool which creates valid vast, saves it and then can read it. Your proposal makes feature with ability to create invalid vast, and to broke any valid media file attribute, protected by signatures of setters, and then you can't read this attribute from vast document instance))) 

I think if you need your dialect, you need to add ability to override class names of elements by passing own media file child to factory. Then you may add any features you want and they will be concrete like 'setMaxBitrate'

**Comment by sokil** [comment]
You may try to use currently undocummented feature with ElementBuilder

```php
class CustomVastDialectElementBuilder extends ElementBuilder
{
    // override there some elements you need with your own classes
}

$elementBuilder = new CustomVastDialectElementBuilder();
$fanctory = new Factory($elementBuilder);
```

Now you create object model of VAST document with your own dialect, where you can add anythink you want

**Comment by davidbonting** [comment]
Thanks!

(after reading #30)
I didn't respond because the PR I made fits my needs, and I thought you only made a suggestion in what to do if we would really proceed with this idea. Sorry ;)

**Comment by sokil** [comment]
Custom element and attribute creation allowed since [0.6](https://github.com/sokil/php-vast/releases/tag/0.6)

**Pull request closed without merging**
