### PR TITLE
two extra attribute can be added to Creative tag (Id and AdId)

### PR DESCRIPTION
**Pull request by farshidboroomand**
Id and adId are **standard** attributes which can be added to `Creative` tag.

### CODE REVIEW

**Comment by sokil** [comment]
Thanks to contribution. Please, add some tests for this methods or add this methods to one of existing tests to increase code coverage

**Review by sokil — CHANGES_REQUESTED** [review]
Add some tests

**Comment by farshidboroomand** [comment]
> Add some tests

**Comment by farshidboroomand** [comment]
> > Add some tests

I would appreciate, if you could kindly edit the test I added to the existing file. cause it did not pass the pipelines. Thank you so much for your time and attention.

**Review by sokil — CHANGES_REQUESTED** [review]
You did not pass pipelines because you add attributes to code and do not add them to XML files. Also you use short array syntax [] and this  fails on old versions of php

**Comment by farshidboroomand** [comment]
Thank you so much for your cooperation :)

**Pull request merged**
