### PR TITLE
New version

### PR DESCRIPTION
**Pull request by dorantor**
Moved away from static create methods, so now classes can be extended. Main reason for this refactoring is improved testability and new functionality for Wrapper Ads(based on VAST3.0).
Major new features: 

- `setError($url)` - on VAST and Ad levels
- `setImpression($url)` - for InLine and Wrapper Ads
- linear creative for Wrapper with Click and Track events(and only them, as defined in VAST3.0)

Also flattened classes structure, so it should be easier to extend\refactor\add.

Backwards compatibility should be broken only at Document creation point.

### CODE REVIEW

**Comment by dorantor** [comment]
It seems php5.4 is minimum requirement to use `(new \Sokil\Vast\Document\Factory())->create('2.0');` syntax.

**Comment by sokil** [comment]
hi! thanks for contribution. To much code to say something about it quickly) i'll check it soon.
As for php5.4, there is no reason to close support of php 5.3 just for syntax sugar (new Foo)->bar()

If you write in tests like below, your code will work in php5.3 and you can use any syntax you want in your php 7.1:
```php
<?php
$factory = new \Sokil\Vast\Document\Factory();
$document = $factory->create('2.0');
```

Moreower about factory: one instance of factory can produce lot of classes. In general case factory will be in DI container, so you will not create factory by yourself with `new`

**Comment by sokil** [comment]
About backwark dompatibility, in your PR you changed namespaces. It is already good case of broken compatibility, if someone overrides class and extends it. Moving class must have good reasons. Also good to previously mark class as deprecated before moving or removing classes.

**Comment by dorantor** [comment]
Agree. Updated UT, so now it should pass. Regarding namespaces - it was end of a long day, when I was writing resume for changes :). So I missed few important details, sorry.

**Comment by dorantor** [comment]
Anyway it's php5.4 :)
I've used traits :)

**Comment by sokil** [comment]
Imho traints is not a good case to add setters to VAST document. Traits is like old good behaviors, used to add some logic to class, not directly corellated witl class (logging, validating, etc). And traits broke SRP because sindle entity like InLine add now broken in to classes. For my opinien copy paste here is better than extending or multiple inheritance.

**Comment by dorantor** [comment]
Traits allowed to move away from inheritance towards composition. I see your point, maybe you right. But c&p smells too bad for me :)
I'll think about it, maybe I'll find a way to keep things decomposed and w/o traits.

**Comment by sokil** [comment]
This is open source. It is bad practise to say people with legacy servers with php 5.3 which works for years that they must update server and their code because you want ot use traits and new syntax sugar )

**Comment by sokil** [comment]
But its not a decomposing. You have different classes and methods inside which accidentally have same name. Your entity must be one single concrete class with all methods inside, or it may extend abstract class if this class is just subcase of some abstract class (due to Liskov substitution principle). 

In your case you add same methods in document and section of document which are semantically different entities.

```php
<?php
$document = (new \Sokil\Vast\Document\Factory())->create('3.0');
$document->setError('//ad.server.com/tracking/error/noad');
```

```php
<?php
$ad1 = $document->createWrapperAdSection()
    ->setId('ad1')
    ->setAdSystem('Ad Server Name')
    ->setVASTAdTagURI('//entertainmentserver.com/vast1.xml')
    ->setError('//ad.server.com/tracking/error')
;

If in future specifications some attributes will be added only to error section of document, but not to wrapper or inline, you will remowe trait and add methods directly to document class.

**Comment by dorantor** [comment]
Done :)

**Comment by dorantor** [comment]
Please let me know if there is anything else what needs to be done. I would like to see it's merged, but I have business requirements also, which demands this functionality ASAP.

**Comment by sokil** [comment]
it's a good reason to add your repo with your fixes to your composer. 

```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/dorantor/php-vast"
        },
```

and add more life to this library ))))

**Comment by dorantor** [comment]
That's what I had to do, in order to move further. But it's always good to bring updated code back to it's origin. It's OSS, after all. So, let me know what should be done in order to make it merged. I'll do my best :)

**Comment by sokil** [comment]
ok) promise to review soon

**Comment by sokil** [comment]
I'v made some changes to your pull request for compatibility with documented api useage, and to be close to specification (Error & Impression allowed to be added multiple times). Please, check new version

**Comment by dorantor** [comment]
Wow. That's a lot of code :) 
I'll take a look and let you know if I'll see anything that can be improved(in my opinion, ofc). Thanks for multiple Error and Impression. It's always a good thing to follow the spec. 
Glad that some of my code found a way to upstream :)

**Pull request merged**
